### ISSUE TITLE
METAR: new link to //aviationweather.gov

### ISSUE THREAD

**Issue by DF1CHB** [joergschultzelutter/mpad#18]
Hi,

Looks like the new link is https://aviationweather.gov/cgi-bin/data/metar.php?ids=EDDL&hours=0&order=id%2C-obs&sep=true

**Comment by joergschultzelutter** [comment]
Thanks for the heads-up! 

For documentation purposes: the new URL is [https://aviationweather.gov/cgi-bin/data/metar.php?ids=EDDL&hours=0&order=id%2C-obs&sep=true&taf=true](https://aviationweather.gov/cgi-bin/data/metar.php?ids=EDDL&hours=0&order=id%2C-obs&sep=true&taf=true)

**Comment by joergschultzelutter** [comment]
Fixed version is up and running, release [0.41](https://github.com/joergschultzelutter/mpad/releases/tag/0.41) fixes the issue. Thanks again for the heads-up! 73!

**Comment by DF1CHB** [comment]
I guess the same issue is affecting WXBOT & WXYO: if you know how to get in touch maybe you could relay this info?

Usage question: when i send EDDL i am getting both METAR & TAF, how to restrict to METAR only?

73

**Comment by joergschultzelutter** [comment]
Well, I am aware of the following sites:

- https://www.aprs.ro/doc/WxYo.php (WXYO)
- https://sites.google.com/site/ki6wjp/wxbot (WXBOT)

I am not in touch with any of these developers, though. Martin might respond to contact requests via e.g. qrz.com.

Regarding the "METAR & TAF" question: Yes, current behavior is that whenever you send the airport code or use the "metar" command, the full set of data is returned. I could amend the behavior in multiple ways:

- separate TAF command, returning TAF info only
- additional "full" command, e.g. "EDDL FULL", returning METAR & TAF

Any preference(s)?

**Comment by DF1CHB** [comment]
I’ll rather go with option 2 aka « FULL ».  The idea behind is when going Robust Packet APRS on HF, the speed is 200 or 600 bd… most of the time the shorter is the better on HF 😉

Thank-you for being openminded 😊

**Comment by joergschultzelutter** [comment]
No worries 😄 . I might apply that FULL keyword logic to wx reports as well. Maybe there is also room for some generic TAF keyword, too. But I need to check how the main program's parser is going to behave when being confronted with these extra keywords. 

This will take a few days to implement (thanks to being snowed-under at work) but should be rather easy to code. I'll create a separate open issue for this task.

**Comment by joergschultzelutter** [comment]
Hey there, I have deployed [a new release](https://github.com/joergschultzelutter/mpad/releases/tag/0.42) to Github (and also to my [live instance](https://aprs.fi/#!z=11&call=a%2FMPAD&timerange=3600&tail=3600)). Changes:

- ```metar``` keyword will now only retrieve METAR data; TAF data will be omitted.
- new keyword ```taf``` will now only retrieve TAF data; METAR data will be omitted.
- add the term ```full``` to any of these two keywords and receive both METAR and TAF data via single command (read: this  is the old behavior). Examples: ```metar eddf full```, ```taf eddf full```.

I guess / hope that this option should satisfy all users and still makes it easier for them to select the actual content that they want to see.

Hope this helps 😄
